<?php

if ( !function_exists( 'mentor_icon_pack_gonzoicon' ) ) {

    function mentor_icon_pack_gonzoicon( $icons ) {

        $icons[] = array(
            'title' => esc_html__( 'Gonzo Icon', 'mentor-icon-pack' ),
            'icons' => array(
                'icon-antenna',
                'icon-archive',
                'icon-arrow-down',
                'icon-arrow-left',
                'icon-arrow-right',
                'icon-arrow-up',
                'icon-article',
                'icon-at',
                'icon-attachment',
                'icon-award',
                'icon-behance',
                'icon-book',
                'icon-bookmark',
                'icon-brackets',
                'icon-browser',
                'icon-cart',
                'icon-category',
                'icon-chat',
                'icon-check',
                'icon-close',
                'icon-cloud',
                'icon-code',
                'icon-coffee',
                'icon-commit',
                'icon-database',
                'icon-date',
                'icon-document',
                'icon-down',
                'icon-download',
                'icon-dribbble',
                'icon-email',
                'icon-eye',
                'icon-facebook',
                'icon-file',
                'icon-flickr',
                'icon-forbidden',
                'icon-garbage',
                'icon-gear',
                'icon-github',
                'icon-googleplus',
                'icon-graph',
                'icon-grid',
                'icon-hamburger',
                'icon-heart',
                'icon-home',
                'icon-hourglass',
                'icon-html5',
                'icon-idea',
                'icon-image',
                'icon-instagram',
                'icon-kebab',
                'icon-key',
                'icon-lab',
                'icon-left',
                'icon-like',
                'icon-link',
                'icon-linkedin',
                'icon-list',
                'icon-location',
                'icon-map',
                'icon-megaphone',
                'icon-microphone',
                'icon-mobile',
                'icon-monitor',
                'icon-music',
                'icon-network',
                'icon-paper',
                'icon-performance',
                'icon-phone',
                'icon-photo',
                'icon-pin',
                'icon-pinterest',
                'icon-portfolio',
                'icon-power',
                'icon-process',
                'icon-project',
                'icon-quote',
                'icon-right',
                'icon-rss',
                'icon-search',
                'icon-send',
                'icon-share',
                'icon-sitemap',
                'icon-skype',
                'icon-star',
                'icon-tag',
                'icon-text',
                'icon-tool',
                'icon-tumblr',
                'icon-twitter',
                'icon-up',
                'icon-upload',
                'icon-url',
                'icon-user',
                'icon-vector',
                'icon-video',
                'icon-vimeo',
                'icon-wordpress',
                'icon-youtube',
            ),
        );

        $icons = array_reverse( $icons );

        return $icons;

    }
    add_filter( 'csf_field_icon_add_icons', 'mentor_icon_pack_gonzoicon' );
}